### ISSUE TITLE
Loosen pin on dbt_utils dependency

### ISSUE THREAD

**Issue by rudeb0y** [re-data/dbt-re-data#94]
dbt_utils is on version 0.9.2 however the pin to the version in re_data is:

packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.7.0", "<0.9.0"]
This makes it tricky when combining with other packages.

Can these requirements but loosened, the above wants to install 0.8.6

**Comment by mateuszklimek** [comment]
Hey @rudeb0y, thanks for bringing this up! I've looked into this, currently main problem issue blocking us with this is fivetran_utils dependency (which also doesn't support dbt_utils 0.9.x, I'm checking with Fivetran on that)

We don't use the Fivetran package heavily, so in case it wouldn't feasible soon, I will see what we can do on our side.

**Comment by rudeb0y** [comment]
Would be great if this was patched

```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.9.4
  - package: dbt-labs/dbt_external_tables
    version: 0.8.2
  - package: dbt-labs/codegen
    version: 0.8.1
  - package: brooklyn-data/dbt_artifacts
    version: 2.1.1
  - package: calogica/dbt_expectations
   # latest does not install along side re_data.. issue raised with re-data
    version: 0.7.0
  #- package: re-data/re_data
   # version: 0.10.5
```
